-- PostgreSQL schema for the EventHub ERD.
-- Monetary amounts use exact decimals. All timestamp values follow UTC.
-- Unique pairs represent one ticket type per booking and one staff assignment per event.
-- Lifecycle fields remain NULL until the corresponding action happens.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE venues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    CONSTRAINT ck_venues_1 CHECK (capacity >= 0)
);

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id INTEGER NOT NULL REFERENCES users(id),
    reviewed_by INTEGER REFERENCES users(id),
    venues_id INTEGER NOT NULL REFERENCES venues(id),
    categories_id INTEGER NOT NULL REFERENCES categories(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    thumbnail_image_url VARCHAR(255) NOT NULL,
    banner_image_url VARCHAR(255) NOT NULL,
    image_zone_url VARCHAR(255),
    start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    cancel_reason VARCHAR(255),
    canceled_at TIMESTAMP(6) WITHOUT TIME ZONE,
    reject_reason VARCHAR(255),
    reviewed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_events_1 CHECK (end_time > start_time)
);

CREATE TABLE ticket_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    events_id INTEGER NOT NULL REFERENCES events(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    image_url VARCHAR(255) NOT NULL,
    price NUMERIC(19,2) NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    remaining_quantity INTEGER NOT NULL,
    sale_start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    sale_end_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT ck_ticket_types_1 CHECK (price >= 0),
    CONSTRAINT ck_ticket_types_2 CHECK (quantity >= 0 AND reserved_quantity >= 0 AND remaining_quantity >= 0),
    CONSTRAINT ck_ticket_types_3 CHECK (reserved_quantity + remaining_quantity <= quantity),
    CONSTRAINT ck_ticket_types_4 CHECK (sale_end_time >= sale_start_time)
);

CREATE TABLE event_staffs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    events_id INTEGER NOT NULL REFERENCES events(id),
    staff_id INTEGER NOT NULL REFERENCES users(id),
    assigned_by INTEGER NOT NULL REFERENCES users(id),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT uk_event_staffs_events_id_staff_id UNIQUE (events_id, staff_id)
);

CREATE TABLE event_guests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    events_id INTEGER NOT NULL REFERENCES events(id),
    name VARCHAR(50),
    role VARCHAR(50),
    description VARCHAR(255),
    image_url VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE user_event_interactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id INTEGER NOT NULL REFERENCES users(id),
    events_id INTEGER NOT NULL REFERENCES events(id),
    interaction_type VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id INTEGER NOT NULL REFERENCES users(id),
    events_id INTEGER NOT NULL REFERENCES events(id),
    total_amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    expired_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_bookings_1 CHECK (total_amount >= 0)
);

CREATE TABLE booking_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookings_id INTEGER NOT NULL REFERENCES bookings(id),
    ticket_types_id INTEGER NOT NULL REFERENCES ticket_types(id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(19,2) NOT NULL,
    CONSTRAINT uk_booking_items_bookings_id_ticket_types_id UNIQUE (bookings_id, ticket_types_id),
    CONSTRAINT ck_booking_items_1 CHECK (quantity > 0),
    CONSTRAINT ck_booking_items_2 CHECK (unit_price >= 0)
);

CREATE TABLE tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_items_id INTEGER NOT NULL REFERENCES booking_items(id),
    checked_in_by INTEGER REFERENCES users(id),
    ticket_code VARCHAR(255) NOT NULL,
    qr_token VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    checked_in_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT uk_tickets_ticket_code UNIQUE (ticket_code),
    CONSTRAINT uk_tickets_qr_token UNIQUE (qr_token)
);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookings_id INTEGER NOT NULL REFERENCES bookings(id),
    transaction_id VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255),
    amount NUMERIC(19,2),
    status VARCHAR(255),
    paid_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT uk_payments_transaction_id UNIQUE (transaction_id),
    CONSTRAINT ck_payments_1 CHECK (amount >= 0)
);

CREATE TABLE refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payments_id INTEGER NOT NULL UNIQUE REFERENCES payments(id),
    refund_transaction_id VARCHAR(255) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(255),
    refunded_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT uk_refunds_refund_transaction_id UNIQUE (refund_transaction_id),
    CONSTRAINT ck_refunds_1 CHECK (amount >= 0),
    CONSTRAINT ck_refunds_2 CHECK (retry_count >= 0)
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(255),
    content VARCHAR(255),
    type VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE ai_conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE ai_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_conversations_id INTEGER NOT NULL REFERENCES ai_conversations(id),
    role VARCHAR(255),
    content VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE organizer_wallets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
    pending_balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    available_balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    withdrawal_pending_balance NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_withdrawn NUMERIC(19,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_organizer_wallets_1 CHECK (pending_balance >= 0 AND available_balance >= 0 AND withdrawal_pending_balance >= 0 AND total_withdrawn >= 0)
);

CREATE TABLE withdrawal_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_wallets_id INTEGER NOT NULL REFERENCES organizer_wallets(id),
    processed_by INTEGER REFERENCES users(id),
    amount NUMERIC(19,2) NOT NULL,
    bank_name VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    requested_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    processed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    reject_reason VARCHAR(255),
    transaction_code VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_withdrawal_requests_1 CHECK (amount > 0)
);

CREATE TABLE payout_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    withdrawal_requests_id INTEGER NOT NULL REFERENCES withdrawal_requests(id),
    amount NUMERIC(19,2) NOT NULL,
    transaction_code VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    failure_reason VARCHAR(255),
    initiated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_payout_transactions_1 CHECK (amount > 0)
);

-- PostgreSQL does not automatically index the referencing side of foreign keys.
CREATE INDEX idx_events_organizer_id ON events (organizer_id);
CREATE INDEX idx_events_reviewed_by ON events (reviewed_by);
CREATE INDEX idx_events_venues_id ON events (venues_id);
CREATE INDEX idx_events_categories_id ON events (categories_id);
CREATE INDEX idx_ticket_types_events_id ON ticket_types (events_id);
CREATE INDEX idx_event_staffs_staff_id ON event_staffs (staff_id);
CREATE INDEX idx_event_staffs_assigned_by ON event_staffs (assigned_by);
CREATE INDEX idx_event_guests_events_id ON event_guests (events_id);
CREATE INDEX idx_user_event_interactions_users_id ON user_event_interactions (users_id);
CREATE INDEX idx_user_event_interactions_events_id ON user_event_interactions (events_id);
CREATE INDEX idx_bookings_users_id ON bookings (users_id);
CREATE INDEX idx_bookings_events_id ON bookings (events_id);
CREATE INDEX idx_booking_items_ticket_types_id ON booking_items (ticket_types_id);
CREATE INDEX idx_tickets_booking_items_id ON tickets (booking_items_id);
CREATE INDEX idx_tickets_checked_in_by ON tickets (checked_in_by);
CREATE INDEX idx_payments_bookings_id ON payments (bookings_id);
CREATE INDEX idx_notifications_users_id ON notifications (users_id);
CREATE INDEX idx_ai_conversations_users_id ON ai_conversations (users_id);
CREATE INDEX idx_ai_messages_ai_conversations_id ON ai_messages (ai_conversations_id);
CREATE INDEX idx_withdrawal_requests_organizer_wallets_id ON withdrawal_requests (organizer_wallets_id);
CREATE INDEX idx_withdrawal_requests_processed_by ON withdrawal_requests (processed_by);
CREATE INDEX idx_payout_transactions_withdrawal_requests_id ON payout_transactions (withdrawal_requests_id);
