-- Email identity is case insensitive, including concurrent registrations.
CREATE UNIQUE INDEX uk_users_email_normalized ON users (LOWER(BTRIM(email)));

-- Each user has one persisted role, including STAFF after assignment.
ALTER TABLE users ADD CONSTRAINT ck_users_base_role
    CHECK (role IN ('ADMIN', 'CUSTOMER', 'ORGANIZER', 'STAFF'));

CREATE TABLE refresh_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id INTEGER NOT NULL REFERENCES users(id),
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_refresh_tokens_hash CHECK (token_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_refresh_tokens_users_id ON refresh_tokens (users_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
